import { extractTopLevelSections } from './utils.js';

/** Preferred top-level key order in v2 config output */
export const TOP_LEVEL_ORDER = ['server', 'http', 'auth', 'frontend', 'userDefaults', 'integrations'];

/**
 * Reorder top-level keys for readable v2 output (http directly after server).
 * @param {Record<string, unknown>} config
 * @returns {Record<string, unknown>}
 */
function orderTopLevelKeys(config) {
  /** @type {Record<string, unknown>} */
  const ordered = {};
  for (const key of TOP_LEVEL_ORDER) {
    if (Object.prototype.hasOwnProperty.call(config, key)) {
      ordered[key] = config[key];
    }
  }
  for (const key of Object.keys(config)) {
    if (!Object.prototype.hasOwnProperty.call(ordered, key)) {
      ordered[key] = config[key];
    }
  }
  return ordered;
}

/**
 * @param {Record<string, unknown>} config
 * @returns {string}
 */
export function emitYaml(config) {
  const header = [
    '# Generated by FileBrowser Quantum config migration tool',
    '# Database values are placeholders, ensure file names match what you expect.',
    '',
  ].join('\n');

  return header + dumpConfig(orderTopLevelKeys(config));
}

/**
 * @param {string} key
 * @param {unknown} value
 * @returns {string}
 */
function dumpTopLevelSection(key, value) {
  return yamlDump({ [key]: value }).trimEnd();
}

/**
 * Merge original section order with v2 preferred order for migrated keys.
 * @param {string[]} originalOrder
 * @param {Record<string, unknown>} config
 * @param {Set<string>} protectedKeys
 * @returns {string[]}
 */
function orderedOutputKeys(originalOrder, config, protectedKeys) {
  /** @type {Set<string>} */
  const seen = new Set();
  /** @type {string[]} */
  const ordered = [];

  const includeKey = (key) =>
    Object.prototype.hasOwnProperty.call(config, key) ||
    (protectedKeys.has(key) && originalOrder.includes(key));

  for (const key of TOP_LEVEL_ORDER) {
    if (seen.has(key) || !includeKey(key)) {
      continue;
    }
    ordered.push(key);
    seen.add(key);
  }

  for (const key of originalOrder) {
    if (seen.has(key) || !includeKey(key)) {
      continue;
    }
    ordered.push(key);
    seen.add(key);
  }

  for (const key of Object.keys(config)) {
    if (!seen.has(key)) {
      ordered.push(key);
      seen.add(key);
    }
  }

  return ordered;
}

/**
 * Emit v2 config while preserving raw YAML for anchor/alias sections.
 * @param {string} raw
 * @param {Record<string, unknown>} config
 * @param {Set<string>} protectedKeys
 * @returns {string}
 */
export function emitYamlPreservingAnchors(raw, config, protectedKeys) {
  const header = [
    '# Generated by FileBrowser Quantum config migration tool',
    '# Database values are placeholders, ensure file names match what you expect.',
    '',
  ].join('\n');

  const ordered = orderTopLevelKeys(config);
  const { preamble, sections, keyOrder } = extractTopLevelSections(raw);
  const keys = orderedOutputKeys(keyOrder, ordered, protectedKeys);

  /** @type {string[]} */
  const parts = [];
  const preambleText = preamble.trimEnd();
  if (preambleText) {
    parts.push(preambleText);
  }

  for (const key of keys) {
    if (protectedKeys.has(key) && sections.has(key)) {
      parts.push(sections.get(key).trimEnd());
    } else if (Object.prototype.hasOwnProperty.call(ordered, key)) {
      parts.push(dumpTopLevelSection(key, ordered[key]));
    }
  }

  return `${header}${parts.join('\n\n')}\n`;
}

/**
 * @param {Record<string, unknown>} config
 * @returns {string}
 */
function dumpConfig(config) {
  return yamlDump(config);
}

/** @type {((doc: unknown) => string)|null} */
let yamlDump = null;

/**
 * @param {(doc: unknown) => string} fn
 */
export function setYamlDumper(fn) {
  yamlDump = fn;
}
